/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly "": {
    readonly "": unique symbol;
    [K: symbol]: T;
  };
}
export declare class Service {}

export interface AuthenticatedIdentity {
  email: string;
  subject: string;
}

export declare function authenticateIapRequest(
  service: ExternalObject<Service>,
  headers: IapRequestHeaders
): Promise<AuthenticatedIdentity | null>;

export interface ChatDto {
  createdAt: string;
  deletedAt?: string;
  id: string;
  lifecycle: string;
  lifecycleRevision: number;
  title: string;
  userId: string;
  visibility: string;
}

export interface ChatHistoryDto {
  chats: ChatDto[];
  hasMore: boolean;
  nextCursor?: string;
}

export declare function createChat(
  service: ExternalObject<Service>,
  id: string,
  userId: string,
  title: string,
  visibility: string,
  createdAt: string
): Promise<ChatDto>;

export declare function createService(): Promise<ExternalObject<Service>>;

export declare function deleteAllChats(
  service: ExternalObject<Service>,
  userId: string
): Promise<number>;

export declare function deleteChat(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string
): Promise<ChatDto>;

export declare function deleteMessagesFrom(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string,
  position: MessagePositionInput
): Promise<number>;

export declare function getChat(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string
): Promise<ChatDto | null>;

export declare function getChatHistory(
  service: ExternalObject<Service>,
  userId: string,
  limit: number,
  startingAfter?: string | undefined | null,
  endingBefore?: string | undefined | null
): Promise<ChatHistoryDto>;

export declare function getMessage(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string,
  messageId: string
): Promise<MessageDto | null>;

export declare function getMessageCount(
  service: ExternalObject<Service>,
  userId: string,
  cutoff: string
): Promise<number>;

export declare function getMessages(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string
): Promise<MessageDto[]>;

export declare function getOrCreateIapUser(
  service: ExternalObject<Service>,
  subject: string,
  email: string
): Promise<UserDto>;

export declare function getSecrets(
  service: ExternalObject<Service>
): SecretEntryDto[];

export declare function getVotes(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string
): Promise<VoteDto[]>;

export interface IapRequestHeaders {
  authenticatedUserEmail?: string;
  authenticatedUserId?: string;
  jwtAssertion?: string;
}

export interface MessageDto {
  attachments: string;
  chatId: string;
  createdAt: string;
  id: string;
  parts: string;
  role: string;
  userId: string;
}

export interface MessageInput {
  attachments: string;
  chatId: string;
  createdAt: string;
  id: string;
  parts: string;
  role: string;
  userId: string;
}

export interface MessagePositionInput {
  createdAt: string;
  id: string;
}

export declare function saveMessages(
  service: ExternalObject<Service>,
  inputs: MessageInput[]
): Promise<MessageDto[]>;

export interface SecretEntryDto {
  key: string;
  value: string;
}

export declare function updateChatTitle(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string,
  title: string
): Promise<ChatDto>;

export declare function updateChatVisibility(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string,
  visibility: string
): Promise<ChatDto>;

export declare function updateMessage(
  service: ExternalObject<Service>,
  input: MessageInput
): Promise<MessageDto>;

export declare function uploadObject(
  service: ExternalObject<Service>,
  data: Buffer,
  filename: string,
  contentType: string
): Promise<UploadResult>;

export interface UploadResult {
  contentType: string;
  pathname: string;
  url: string;
}

export interface UserDto {
  createdAt: string;
  email: string;
  iapSubject?: string;
  id: string;
  updatedAt: string;
}

export interface VoteDto {
  chatId: string;
  isUpvoted: boolean;
  messageId: string;
}

export declare function voteMessage(
  service: ExternalObject<Service>,
  userId: string,
  chatId: string,
  messageId: string,
  isUpvoted: boolean
): Promise<VoteDto>;
