/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly "": {
    readonly "": unique symbol;
    [K: symbol]: T;
  };
}
export declare class Service {}

export declare function createService(): Promise<ExternalObject<Service>>;

export declare function uploadObject(
  service: ExternalObject<Service>,
  data: Buffer,
  filename: string,
  contentType: string
): Promise<UploadResult>;

export interface UploadResult {
  contentType: string;
  pathname: string;
  url: string;
}
