/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function uploadObject(
  data: Buffer,
  filename: string,
  contentType: string
): Promise<UploadResult>;

export interface UploadResult {
  contentType: string;
  pathname: string;
  url: string;
}
