name: Lint
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Test
        run: cargo test --workspace --all-targets
      - name: Check hydrate target
        run: cargo check -p chatbot-web --target wasm32-unknown-unknown --no-default-features --features hydrate
